NUMBER 1 ACTIVITY

In [ ]:
#Number 1 :Importing
#importing numpy as np

import numpy as np

In [ ]:
#Number 1 :Creating Arrays
#Create a one-dimentional and two dimentional array using np.array().

# The 1 dimensional array
arr_1d = np.array([1,2,3,4,5])

# The 2 dimensional array
arr_2d = np.array([[1,2,3],[4,5,6]])

print("1 Dimensional Array: ",arr_1d)
print("2 Dimentional Array:\n",arr_2d)


1 Dimensional Array:  [1 2 3 4 5]
2 Dimentional Array:
 [[1 2 3]
 [4 5 6]]


NUMBER 2 ACTIVITY

In [ ]:
#Number 2: Basic Array Operations
#Perform element-wise addition, subtraction, multiplication, and divition on the arrays.

#ADDITION
arr_sum = arr_1d + 5
print("Element-wise addtion: ",arr_sum,"\n")

#SUBTRACTION
arr_difference = arr_sum - 2
print("Element-wise subtraction: ",arr_difference,"\n")

#MULTIPLICATION
arr_product = arr_difference * 3
print("Element-wise multiplication: ",arr_product,"\n")

#DIVISION
arr_division = arr_product / 3
print("Element-wise division: ",arr_division,"\n")

Element-wise addtion:  [ 6  7  8  9 10] 

Element-wise subtraction:  [4 5 6 7 8] 

Element-wise multiplication:  [12 15 18 21 24] 

Element-wise division:  [4. 5. 6. 7. 8.] 



In [ ]:
# Number 2: continuation
#Using array indexing and slicing to extract specific elements or sub-arrays

#EXTRACT AND SLICE 'ADDITION'
arr_subsum= arr_1d[0] + arr_1d[4]
print("Sum of first and last element: ",arr_subsum,"\n")

#EXTRACT AND SLICE 'SUBTRACTION'
arr_subdiff = arr_1d[0] - arr_1d[4]
print("Difference of first and last element: ",arr_subdiff,"\n")

#EXTRACT AND SLICE 'MULTIPLICATION'
arr_subproduct = arr_1d[1] * arr_1d[4]
print("Product of first and last element: ",arr_subproduct,"\n")

#EXTRACT AND SLICE 'DIVISION'
arr_subdivision = arr_1d[3] / arr_1d[1]
print("Division of first and last element: ",arr_subdivision,"\n")

Sum of first and last element:  6 

Difference of first and last element:  -4 

Product of first and last element:  10 

Division of first and last element:  2.0 



NUMBER 3 ACTIVITY

In [ ]:
#Number 3: Reshaping Array
#Reshape 1D array to 2D array

arr_3 = np.array([1,2,3,4,5,6])
reshaped_arr = arr_1d.reshape(5,1)

print("Reshaped 1D array to 2D array:\n",reshaped_arr)

Reshaped 1D array to 2D array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
#Number 3: Transposing Array
#Transpose the 2D array

transpossed_arr = arr_2d.transpose()
print("Transpossed 2D array:\n",transpossed_arr)

Transpossed 2D array:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Number 3: Array Indexing and slicing

print ("First element of 1D Array: ",arr_1d[0])
print ("Second row of 2D arrary: ", arr_2d[1,:])

First element of 1D Array:  1
Second row of 2D arrary:  [4 5 6]


NUMBER 4 ACTIVITY

In [ ]:
#Number 4: Create a 3x3 Numpy array with values ranging 1 to 9
#NUMPY IS ALREADY DECLARED AT THE TOP

act_array = np.arange(1, 10).reshape(3, 3)
print(act_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Number 4: Find the sum,mean and standard deviation of the array

sum_array = np.sum(act_array)
mean_array = np.mean(act_array)
std_array = np.std(act_array)

print("Sum of the array: ", sum_array)
print("Mean of the array: ",mean_array)
print("Standard deviation of the array: ",std_array)

Sum of the array:  45
Mean of the array:  5.0
Standard deviation of the array:  2.581988897471611


In [ ]:
#Number 4: Extract the subarray that consists of the first two rows and first two columns

extracted_subarray = act_array[:2, :2]
print(extracted_subarray)

[[1 2]
 [4 5]]
